#ifndef AMIT_PROJECT_WTCHDG_H_
#define AMIT_PROJECT_WTCHDG_H_
typedef enum _WTCHDG_PRESCALLER_t
{
    WTCHDG_PRESCALLER_16K ,
    WTCHDG_PRESCALLER_32K ,
    WTCHDG_PRESCALLER_64k ,
    WTCHDG_PRESCALLER_128K ,
    WTCHDG_PRESCALLER_256K ,
    WTCHDG_PRESCALLER_512K ,
    WTCHDG_PRESCALLER_1024K ,
    WTCHDG_PRESCALLER_2048K ,
    NUM_OF_WTCHDG_PRESCALLERS
} WTCHDG_PRESCALLER_t;
typedef enum _WTCHDG_STD_ERR_t
{
    WTCHDG_OK ,
    WTCHDG_ERR_PRESC
} WTCHDG_STD_ERR_t;
WTCHDG_STD_ERR_t WTCHDG_setPrescaller ( WTCHDG_PRESCALLER_t prescSetting );
WTCHDG_PRESCALLER_t WTCHDG_getPrescaller ( void );
void WTCHDG_enable ( void );
void WTCHDG_disable ( void );
void WTCHDG_reset ( void );
#endif
